#!/usr/bin/bash

if [ $# -eq 0 ]; then
	echo "Usage: $0 {toggle|on|off}"
	exit 1
fi

on() {
	echo 1 > /proc/acpi/ibm/lcdshadow
}

off() {
	echo 0 > /proc/acpi/ibm/lcdshadow
}

toggle() {
	status=$(awk '/status:/ {print $2}' /proc/acpi/ibm/lcdshadow)
	if [ "$status" -eq "0" ]; then
		on
	else
		off
	fi
}

case "$1" in
	toggle)
		toggle
		;;
	on)
		on
		;;
	off)
		off
		;;
	*)
		echo "Invalid option: $1"
		echo "Usage: $0 {toggle|on|off}"
		exit 1
		;;
esac
